import { FastifyInstance } from "fastify";

export default async function (app: FastifyInstance) {
  app.get("/health", async () => {
    return { status: "ok", timestamp: new Date().toISOString() };
  });

  app.get("/ping", async () => {
    return { message: "pong" };
  });

  app.get("/suggestions", async () => {
    // Mock AI health suggestions - in production this would be generated by AI
    return [
      {
        id: "1",
        type: "exercise",
        title: "Regular Exercise Recommended",
        description: "Based on your recent reports, 30 minutes of daily exercise could improve your health score",
        priority: "medium"
      },
      {
        id: "2",
        type: "vitamin",
        title: "Vitamin D Levels Improving",
        description: "Your vitamin D levels have increased by 15% since last month",
        priority: "low"
      },
      {
        id: "3",
        type: "checkup",
        title: "Schedule Follow-up",
        description: "It's been 3 months since your last comprehensive check-up",
        priority: "high"
      }
    ];
  });
}
